```yaml
trigger:
  - main

pool:
  vmImage: ubuntu-latest

variables:
  terraformWorkingDirectory: '$(System.DefaultWorkingDirectory)/Explict_dependancy'

steps:

- task: TerraformInstaller@1
  displayName: 'Install Terraform'
  inputs:
    terraformVersion: 'latest'

- script: |
    terraform init
  displayName: 'Terraform Init'
  workingDirectory: '$(terraformWorkingDirectory)'

- script: |
    terraform validate
  displayName: 'Terraform Validate'
  workingDirectory: '$(terraformWorkingDirectory)'

- task: AzureCLI@2
  displayName: 'Terraform Plan'
  inputs:
    azureSubscription: 'YOUR-SERVICE-CONNECTION-NAME'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    workingDirectory: '$(terraformWorkingDirectory)'
    inlineScript: |
      terraform plan
```
